#!/bin/sh
#
# Start/stop dhcpcd
#

DAEMON=/sbin/dhcpcd
CONFIG=/etc/dhcpcd.conf
PIDFILE=/var/run/dhcpcd.pid

[ -f $CONFIG ] || exit 0

case "$1" in
  start)
    {
        while [ $(ps | grep "S40network start" | wc -l) -gt 1 ];
        do
            echo "$0 is waiting for S40network to be ready"
            usleep 200000
        done
	echo "Starting dhcpcd..."
	start-stop-daemon -S -x "$DAEMON" -p "$PIDFILE" -- -f "$CONFIG"
    }&
	;;
  stop)
	echo "Stopping dhcpcd..."
	start-stop-daemon -K -x "$DAEMON" -p "$PIDFILE" -o
	;;
  reload|force-reload)
	echo "Reloading dhcpcd configuration..."
	"$DAEMON" -s reload
	;;
  restart)
	"$0" stop
	sleep 1 # Prevent race condition: ensure dhcpcd stops before start.
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|force-reload}"
	exit 1
esac
