#!/bin/sh
#
# Starts the input_eventd daemon.
#


case "$1" in
  start)
    # load firmware
    dsp_util --load --dsp hifi4a -f dspbootA.bin
    # Launch DSP rtos
    dsp_util -S --dsp hifi4a
    ;;
  stop)
    echo -n "Do thing: "
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
