#!/bin/sh
#
# rtspatt
#

PID_FILE=/tmp/rtspatt.pid
RTSP_VIDEO_DEVICE=${RTSP_VIDEO_DEVICE:-"/dev/video0"}
export RTSP_PORT=${RTSP_PORT:-554}
export RTSP_RESOLUTION=${RTSP_RESOLUTION:-"1280x720"}
export ENABLE_TIME_OVERLAY=${ENABLE_TIME_OVERLAY:-"false"}
export RTSP_ENABLE_FACE_DETECTION=${RTSP_ENABLE_FACE_DETECTION:-"true"}
export RTSP_USE_X265ENC=${RTSP_USE_X265ENC:-"true"}

DAEMON=rtspatt
DAEMON_ARGS="-i $RTSP_VIDEO_DEVICE"

start() {
  if [ -f $PID_FILE ] && kill -0 $(cat $PID_FILE); then
    echo "$DAEMON already running"
    return 1
  fi
  printf "Starting rtspatt: "
  $DAEMON $DAEMON_ARGS &
  echo $! > $PID_FILE
}

stop() {
  if [ ! -f "$PID_FILE" ] || ! kill -0 $(cat "$PID_FILE"); then
    echo "$DAEMON not running"
    return 1
  fi
  printf "Stopping $DAEMON "
  kill $(cat $PID_FILE) && rm -f $PID_FILE
  echo "$DAEMON stopped"
}
restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

