#!/bin/sh

NAME1=bsa_server
DAEMON1=/usr/bin/$NAME1
PIDFILE1=/var/run/$NAME1.pid

NAME2=app_manager
DAEMON2=/usr/bin/$NAME2
PIDFILE2=/var/run/$NAME2.pid

NAME3=app_avk
DAEMON3=/usr/bin/$NAME3
PIDFILE3=/var/run/$NAME3.pid

HW_PLATFORM=$(cat /proc/device-tree/amlogic-dt-id | awk -F "_" '{print $2}')
if [ "${HW_PLATFORM}" == "s400" ];then
    hcd_file="/etc/wifi/6255/BCM4345C0.hcd"
elif [ "${HW_PLATFORM}" == "s420" ];then
    hcd_file="/etc/wifi/4356/bcm4356a2.hcd"
else
    echo "$0: not s400/s420, exit!"
    exit 1
fi
#echo "hcd_file = $hcd_file"

case "$1" in
    start)

    echo 0 > /sys/class/rfkill/rfkill0/state
    sleep 1
    echo 1 > /sys/class/rfkill/rfkill0/state
    sleep 1

    cd /etc/bsa/config
    echo "start broadcom bluetooth server bsa_sever"
    start-stop-daemon -S  -m -p $PIDFILE1 -x $DAEMON1 -- -r 13 -all=0 -b /etc/bsa/config/btsnoop.log -p $hcd_file -d /dev/ttyS1 &
    sleep 2

    echo "start broadcom bluetooth app_manager"
    start-stop-daemon -S  -m -p $PIDFILE2 -x $DAEMON2 -- -s &

    echo "start broadcom bluetooth app_avk"
    start-stop-daemon -S  -m -p $PIDFILE3 -x $DAEMON3 -- -s &
    sleep 1


    echo "#########act as a bluetooth music player#########"
    app_socket avk 2
    cd - > /dev/null
    sleep 2
    echo "


|-----bluetooth music player is ready for connections------|"

        ;;
    netready|netup|netdown|netchange) ;;
    stop)
        echo -n "Stopping broadcom bluetooth server & app"
        app_socket avk 99
        app_socket manager 99
        sleep 1
        start-stop-daemon -K -o -p $PIDFILE1
        sleep 2
        rm -f $PIDFILE1
        rm -f $PIDFILE2
        rm -f $PIDFILE3
        sleep 2
        echo 0 > /sys/class/rfkill/rfkill0/state
        echo "


|-----bluetooth music player is shutdown-----|"

        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?

