void glActiveTexture(void) { return; }
void glAttachShader(void) { return; }
void glBindAttribLocation(void) { return; }
void glBindBuffer(void) { return; }
void glBindFramebuffer(void) { return; }
void glBindRenderbuffer(void) { return; }
void glBindTexture(void) { return; }
void glBlendColor(void) { return; }
void glBlendEquation(void) { return; }
void glBlendEquationSeparate(void) { return; }
void glBlendFunc(void) { return; }
void glBlendFuncSeparate(void) { return; }
void glBufferData(void) { return; }
void glBufferSubData(void) { return; }
void glCheckFramebufferStatus(void) { return; }
void glClear(void) { return; }
void glClearColor(void) { return; }
void glClearDepthf(void) { return; }
void glClearStencil(void) { return; }
void glColorMask(void) { return; }
void glCompileShader(void) { return; }
void glCompressedTexImage2D(void) { return; }
void glCompressedTexSubImage2D(void) { return; }
void glCopyTexImage2D(void) { return; }
void glCopyTexSubImage2D(void) { return; }
void glCreateProgram(void) { return; }
void glCreateShader(void) { return; }
void glCullFace(void) { return; }
void glDeleteBuffers(void) { return; }
void glDeleteFramebuffers(void) { return; }
void glDeleteProgram(void) { return; }
void glDeleteRenderbuffers(void) { return; }
void glDeleteShader(void) { return; }
void glDeleteTextures(void) { return; }
void glDepthFunc(void) { return; }
void glDepthMask(void) { return; }
void glDepthRangef(void) { return; }
void glDetachShader(void) { return; }
void glDisable(void) { return; }
void glDisableVertexAttribArray(void) { return; }
void glDrawArrays(void) { return; }
void glDrawElements(void) { return; }
void glEGLImageTargetRenderbufferStorageOES(void) { return; }
void glEGLImageTargetTexture2DOES(void) { return; }
void glEnable(void) { return; }
void glEnableVertexAttribArray(void) { return; }
void glFinish(void) { return; }
void glFlush(void) { return; }
void glFramebufferRenderbuffer(void) { return; }
void glFramebufferTexture2D(void) { return; }
void glFrontFace(void) { return; }
void glGenBuffers(void) { return; }
void glGenFramebuffers(void) { return; }
void glGenRenderbuffers(void) { return; }
void glGenTextures(void) { return; }
void glGenerateMipmap(void) { return; }
void glGetActiveAttrib(void) { return; }
void glGetActiveUniform(void) { return; }
void glGetAttachedShaders(void) { return; }
void glGetAttribLocation(void) { return; }
void glGetBooleanv(void) { return; }
void glGetBufferParameteriv(void) { return; }
void glGetError(void) { return; }
void glGetFloatv(void) { return; }
void glGetFramebufferAttachmentParameteriv(void) { return; }
void glGetIntegerv(void) { return; }
void glGetProgramInfoLog(void) { return; }
void glGetProgramiv(void) { return; }
void glGetRenderbufferParameteriv(void) { return; }
void glGetShaderInfoLog(void) { return; }
void glGetShaderPrecisionFormat(void) { return; }
void glGetShaderSource(void) { return; }
void glGetShaderiv(void) { return; }
void glGetString(void) { return; }
void glGetTexParameterfv(void) { return; }
void glGetTexParameteriv(void) { return; }
void glGetUniformLocation(void) { return; }
void glGetUniformfv(void) { return; }
void glGetUniformiv(void) { return; }
void glGetVertexAttribPointerv(void) { return; }
void glGetVertexAttribfv(void) { return; }
void glGetVertexAttribiv(void) { return; }
void glHint(void) { return; }
void glIsBuffer(void) { return; }
void glIsEnabled(void) { return; }
void glIsFramebuffer(void) { return; }
void glIsProgram(void) { return; }
void glIsRenderbuffer(void) { return; }
void glIsShader(void) { return; }
void glIsTexture(void) { return; }
void glLineWidth(void) { return; }
void glLinkProgram(void) { return; }
void glPixelStorei(void) { return; }
void glPolygonOffset(void) { return; }
void glReadPixels(void) { return; }
void glReleaseShaderCompiler(void) { return; }
void glRenderbufferStorage(void) { return; }
void glSampleCoverage(void) { return; }
void glScissor(void) { return; }
void glShaderBinary(void) { return; }
void glShaderSource(void) { return; }
void glStencilFunc(void) { return; }
void glStencilFuncSeparate(void) { return; }
void glStencilMask(void) { return; }
void glStencilMaskSeparate(void) { return; }
void glStencilOp(void) { return; }
void glStencilOpSeparate(void) { return; }
void glTexImage2D(void) { return; }
void glTexParameterf(void) { return; }
void glTexParameterfv(void) { return; }
void glTexParameteri(void) { return; }
void glTexParameteriv(void) { return; }
void glTexSubImage2D(void) { return; }
void glUniform1f(void) { return; }
void glUniform1fv(void) { return; }
void glUniform1i(void) { return; }
void glUniform1iv(void) { return; }
void glUniform2f(void) { return; }
void glUniform2fv(void) { return; }
void glUniform2i(void) { return; }
void glUniform2iv(void) { return; }
void glUniform3f(void) { return; }
void glUniform3fv(void) { return; }
void glUniform3i(void) { return; }
void glUniform3iv(void) { return; }
void glUniform4f(void) { return; }
void glUniform4fv(void) { return; }
void glUniform4i(void) { return; }
void glUniform4iv(void) { return; }
void glUniformMatrix2fv(void) { return; }
void glUniformMatrix3fv(void) { return; }
void glUniformMatrix4fv(void) { return; }
void glUseProgram(void) { return; }
void glValidateProgram(void) { return; }
void glVertexAttrib1f(void) { return; }
void glVertexAttrib1fv(void) { return; }
void glVertexAttrib2f(void) { return; }
void glVertexAttrib2fv(void) { return; }
void glVertexAttrib3f(void) { return; }
void glVertexAttrib3fv(void) { return; }
void glVertexAttrib4f(void) { return; }
void glVertexAttrib4fv(void) { return; }
void glVertexAttribPointer(void) { return; }
void glViewport(void) { return; }
