void vgDestroyImage(void) { return; }
void vgLoadIdentity(void) { return; }
void vgModifyPathCoords(void) { return; }
void vgSeparableConvolve(void) { return; }
void vgCreatePaint(void) { return; }
void vgPaintPattern(void) { return; }
void vgConvolve(void) { return; }
void vgRotate(void) { return; }
void vgSetPixels(void) { return; }
void vgCopyPixels(void) { return; }
void vgLoadMatrix(void) { return; }
void vgCopyImage(void) { return; }
void vgPathTransformedBounds(void) { return; }
void vgPointAlongPath(void) { return; }
void vgColorMatrix(void) { return; }
void vgFinish(void) { return; }
void vgGetParameteri(void) { return; }
void vgInterpolatePath(void) { return; }
void vgGetParameterVectorSize(void) { return; }
void vgSetColor(void) { return; }
void vgSetGlyphToImage(void) { return; }
void vgMask(void) { return; }
void vgDrawGlyphs(void) { return; }
void vgGetiv(void) { return; }
void vgImageSubData(void) { return; }
void vgGeti(void) { return; }
void vgCreateImage(void) { return; }
void vgClearImage(void) { return; }
void vgTranslate(void) { return; }
void vgSetfv(void) { return; }
void vgGetColor(void) { return; }
void vgGetVectorSize(void) { return; }
void vgGetParameterf(void) { return; }
void vgGetPathCapabilities(void) { return; }
void vgDestroyFont(void) { return; }
void vgDestroyPath(void) { return; }
void vgGetPaint(void) { return; }
void vgSetParameterf(void) { return; }
void vgScale(void) { return; }
void vgGetfv(void) { return; }
void vgSetGlyphToPath(void) { return; }
void vgHardwareQuery(void) { return; }
void vgFillMaskLayer(void) { return; }
void vgCreateMaskLayer(void) { return; }
void vgLookup(void) { return; }
void vgMultMatrix(void) { return; }
void vgGetf(void) { return; }
void vgSeti(void) { return; }
void vgRenderToMask(void) { return; }
void vgGetMatrix(void) { return; }
void vgLookupSingle(void) { return; }
void vgFlush(void) { return; }
void vgClear(void) { return; }
void vgGetParent(void) { return; }
void vgPathLength(void) { return; }
void vgDrawImage(void) { return; }
void vgSetPaint(void) { return; }
void vgRemovePathCapabilities(void) { return; }
void vgGetParameterfv(void) { return; }
void vgGetPixels(void) { return; }
void vgCreateFont(void) { return; }
void vgCopyMask(void) { return; }
void vgAppendPathData(void) { return; }
void vgGetImageSubData(void) { return; }
void vgSetParameteri(void) { return; }
void vgPathBounds(void) { return; }
void vgSetParameterfv(void) { return; }
void vgSetf(void) { return; }
void vgDestroyPaint(void) { return; }
void vgWritePixels(void) { return; }
void vgGetParameteriv(void) { return; }
void vgGetError(void) { return; }
void vgReadPixels(void) { return; }
void vgDrawGlyph(void) { return; }
void vgGaussianBlur(void) { return; }
void vgClearGlyph(void) { return; }
void vgTransformPath(void) { return; }
void vgShear(void) { return; }
void vgSetParameteriv(void) { return; }
void vgGetString(void) { return; }
void vgClearPath(void) { return; }
void vgChildImage(void) { return; }
void vgDestroyMaskLayer(void) { return; }
void vgSetiv(void) { return; }
void vgAppendPath(void) { return; }
void vgDrawPath(void) { return; }
void vgCreatePath(void) { return; }
void vgCreateEGLImageTargetKHR(void) { return; }

