#!/bin/sh
#
# onvif_rtsp
#

PID_FILE=/tmp/onvif_rtsp.pid

export RTSP_NETWORK_ADDRESS=${RTSP_NETWORK_ADDRESS:-"0.0.0.0"}
export RTSP_NETWORK_PORT=${RTSP_NETWORK_PORT:-"554"}
export RTSP_NETWORK_ROUTE=${RTSP_NETWORK_ROUTE:-"/live.sdp"}
export RTSP_AUTH_USERNAME=${RTSP_AUTH_USERNAME:-""}
export RTSP_AUTH_PASSWORD=${RTSP_AUTH_PASSWORD:-""}
export IPC_VIDEO_DEVICE=${IPC_VIDEO_DEVICE:-"/dev/video0"}
export IPC_VIDEO_FRAMERATE=${IPC_VIDEO_FRAMERATE:-"30"}
export IPC_VIDEO_RESOLUTION=${IPC_VIDEO_RESOLUTION:-"1920x1080"}
export IPC_VIDEO_BITRATE=${IPC_VIDEO_BITRATE:-"2000"}
export IPC_VIDEO_GOP=${IPC_VIDEO_GOP:-"15"}
export IPC_VIDEO_USE_X265ENC=${IPC_VIDEO_USE_X265ENC:-"true"}
export IPC_ISP_WDR_ENABLED=${IPC_ISP_WDR_ENABLED:-"false"}
#export IPC_AUDIO_DEVICE=${IPC_AUDIO_DEVICE:-""}
#export IPC_AUDIO_BITRATE=${IPC_AUDIO_BITRATE:-""}
#export IPC_AUDIO_SAMPLERATE=${IPC_AUDIO_SAMPLERATE:-""}
#export IPC_AUDIO_CODEC=${IPC_AUDIO_CODEC:-""}
#export IPC_BACKCHANNEL_CLOCK_RATE=${IPC_BACKCHANNEL_CLOCK_RATE:-""}
#export IPC_BACKCHANNEL_ENCODING=${IPC_BACKCHANNEL_ENCODING:-""}
#export IPC_BACKCHANNEL_DEVICE=${IPC_BACKCHANNEL_DEVICE:-""}
export IPC_OVERLAY_OPTIONS=${IPC_OVERLAY_OPTIONS:-""}
export IPC_FACE_DETECTION_ENABLED=${IPC_FACE_DETECTION_ENABLED:-"true"}
export IPC_IMAGE_CAPTURE_ENABLED=${IPC_IMAGE_CAPTURE_ENABLED:-"false"}
export IPC_IMAGE_CAPTURE_LOCATION=${IPC_IMAGE_CAPTURE_LOCATION:-""}
export IPC_DEBUG_DISABLE_AUDIO=${IPC_DEBUG_DISABLE_AUDIO:-"true"}
export IPC_DEBUG_DISABLE_BACKCHANNEL=${IPC_DEBUG_DISABLE_BACKCHANNEL:-"true"}

DAEMON=onvif_rtsp
DAEMON_ARGS=""

start() {
  if [ -f $PID_FILE ] && kill -0 $(cat $PID_FILE); then
    echo "$DAEMON already running"
    return 1
  fi
  printf "Starting onvif rtsp server..."
  eval "$DAEMON $DAEMON_ARGS &"
  echo $! > $PID_FILE
}

stop() {
  if [ ! -f "$PID_FILE" ] || ! kill -0 $(cat "$PID_FILE"); then
    echo "$DAEMON not running"
    return 1
  fi
  printf "Stopping $DAEMON "
  kill $(cat $PID_FILE) && rm -f $PID_FILE
  echo "$DAEMON stopped"
}
restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

