#!/bin/sh

CONFIG=/etc/AlexaClientSDKConfig.json
PROCESS=/usr/bin/SampleApp

case "$1" in
    stop|restart) ;;
    start)
    modprobe snd-aloop

    amixer_ctr=`amixer controls | grep "Loopback Enable"`
    loop_id=${amixer_ctr%%,*}
    amixer cset $loop_id 1

    /usr/bin/speaker_process &
    ;;
    netready)
    /etc/init.d/S49ntp stop
    /etc/init.d/S49ntp start
    sleep 2
    if [ -f $CONFIG ];then
        cd /usr/bin/
	./SampleApp $CONFIG NONE back &
	cd /
    else
        echo "avs start fail: not found config file $CONFIG!!!"
    fi
    ;;
    netup|netdown|netchange) ;;
    *)
    echo "Usage: $0 {start|stop|restart|netready|netup|netdown|netchange}"
    exit 1
    ;;
esac
