#!/bin/sh

CONFIG=/etc/AlexaClientSDKConfig.json
PROCESS=/usr/bin/SampleApp

case "$1" in
    start|stop|restart) ;;
    netready)
    amixer cset numid=40,iface=MIXER,name='Loopback Enable' 1
    /etc/init.d/S49ntp stop
    /etc/init.d/S49ntp start
    sleep 2
    if [ -f $CONFIG ];then
        #amixer cset numid=40,iface=MIXER,name='Loopback Enable' 1
        cd /usr/bin/
	./SampleApp $CONFIG NONE back &
	cd /
    else
        echo "avs start fail: not found config file $CONFIG!!!"
    fi
    ;;
    netup|netdown|netchange) ;;
    *)
    echo "Usage: $0 {start|stop|restart|netready|netup|netdown|netchange}"
    exit 1
    ;;
esac
