#!/bin/sh

NAME=wpa_supplicant
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
POWERCTL=/usr/bin/wifi_power
MULTI_WIFI=/usr/bin/multi_wifi_load_driver

case "$1" in
    start)
	    board_name=`cat /proc/device-tree/amlogic-dt-id`
	    case ${board_name} in
			"gxl_p401_2g")
				exit 0
				;;
	    esac

        echo "Starting supplicant..."
        mkdir -p -m 0644 /var/lib/wifi
        $POWERCTL 1
        $MULTI_WIFI station 1
        sleep 2
        start-stop-daemon -S -m -p $PIDFILE -b -x $DAEMON -- -Dnl80211 -iwlan0 -c/etc/wpa_supplicant.conf 
        sleep 2
        ifconfig wlan0 &> /dev/null
        if [ $? -eq 0 ]; then
            dhcpcd -A wlan0
        fi
        ;;
    stop)
        echo -n "Stopping supplicant..."
        start-stop-daemon -K -o -p $PIDFILE
        sleep 2
        rm -f $PIDFILE
        $MULTI_WIFI station 0
        $POWERCTL 0
        ;;
    restart|reload)
        start-stop-daemon -K -s HUP -n wpa_supplicant
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

