#!/bin/sh

NAME=wpa_supplicant
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
POWERCTL=/usr/bin/wifi_power

case "$1" in
    start)
		echo "Starting supplicant..."
		start-stop-daemon -S -m -p $PIDFILE -b -x $DAEMON -- -Dnl80211 -iwlan0 -c/etc/wpa_supplicant.conf
		sleep 2
		ifconfig wlan0 &> /dev/null

		if [ $? -eq 0 ]; then
			cnt=1
			while [ $cnt -lt 5 ]; do
				status=`wpa_cli status`
				status=${status##*wpa_state=} 
				status=$(echo $status |awk '{print $1}') 
				if [ "$status" = "COMPLETED" ];then
					dhcpcd wlan0 &
					break
				elif [ "$status" = "DISCONNECTED" ];then
					break;
				else
					cnt=$((cnt + 1))
					sleep 1
				fi
			done
		fi
        ;;
    stop)
        echo -n "Stopping supplicant..."
        start-stop-daemon -K -o -p $PIDFILE
        sleep 2
        rm -f $PIDFILE
        $POWERCTL 0
        ;;
    restart|reload)
        start-stop-daemon -K -s HUP -n wpa_supplicant
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

