#!/bin/sh

usb_rndis_init()
{
	mount -t configfs none /sys/kernel/config
 	mkdir /sys/kernel/config/usb_gadget/amlogic
 	cd /sys/kernel/config/usb_gadget/amlogic
	echo 0x18D1 > idVendor
 	echo 0x4e26 > idProduct
	mkdir strings/0x409
	echo 0123456789ABCDEF > strings/0x409/serialnumber
	echo amlogic > strings/0x409/manufacturer
	echo p212 > strings/0x409/product
	mkdir configs/amlogic.1
	mkdir configs/amlogic.1/strings/0x409
	echo rndis > configs/amlogic.1/strings/0x409/configuration
	echo 500 > configs/amlogic.1/MaxPower
	mkdir functions/rndis.rndis
	ln -s functions/rndis.rndis configs/amlogic.1
	echo ff400000.dwc2_a > /sys/kernel/config/usb_gadget/amlogic/UDC
	cd /
}

case "$1" in
  start)
      	sleep 6
    	cat /proc/device-tree/amlogic-dt-id  | grep "skt"
    	if [ $? -eq 0 ]
    	then
        	usb_dir=/sys/kernel/config/usb_gadget/amlogic
        	if [ ! -d ${usb_dir} ]
        	then
            	usb_rndis_init
        	fi
    	fi
		;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?

