#!/bin/sh

# Weston
[ -d /run/wayland ] || mkdir -p /run/wayland
chmod 0700 /run/wayland

export XDG_RUNTIME_DIR=/run/wayland/

NAME=weston
START_PARAMTERS="--config=/etc/aml-weston.ini --backend=fbdev-backend.so --tty=1 --device=/dev/fb0 --idle-time=0 --log=/tmp/weston.log"
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid

case "$1" in
     start)
         echo "Starting weston..."
         start-stop-daemon -S -m -p $PIDFILE -b -x $DAEMON -- $START_PARAMTERS
         ;;
     stop)
         echo -n "Stopping weston..."
         start-stop-daemon -K -o -p $PIDFILE
         rm -f $PIDFILE
         ;;
     *)
         echo "Usage: $0 {start|stop|restart}"
         exit 1
esac
 
exit $?

