Index: uboot-2015-dev/bl33/Makefile
===================================================================
--- uboot-2015-dev.orig/bl33/Makefile	2017-07-20 15:29:13.958496982 +0800
+++ uboot-2015-dev/bl33/Makefile	2017-07-20 15:47:27.511958613 +0800
@@ -246,8 +246,8 @@
 CROSS_COMPILE ?=
 endif
 
-export CROSS_COMPILE=/opt/gcc-linaro-aarch64-none-elf-4.8-2013.11_linux/bin/aarch64-none-elf-
-export CROSS_COMPILE_T32=/opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-
+export CROSS_COMPILE=aarch64-none-elf-
+export CROSS_COMPILE_T32=arm-none-eabi-
 
 KCONFIG_CONFIG	?= .config
 export KCONFIG_CONFIG
