Index: uboot-repo/bl33/Makefile
===================================================================
--- uboot-repo.orig/bl33/Makefile	2018-09-19 19:46:11.478421599 +0800
+++ uboot-repo/bl33/Makefile	2018-09-19 19:47:55.552986787 +0800
@@ -246,8 +246,10 @@ ifeq ($(HOSTARCH),$(ARCH))
 CROSS_COMPILE ?=
 endif
 
-export CROSS_COMPILE=/opt/gcc-linaro-aarch64-none-elf-4.8-2013.11_linux/bin/aarch64-none-elf-
-export CROSS_COMPILE_T32=/opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-
+CROSS_COMPILE=aarch64-none-elf-
+CROSS_COMPILE_T32=arm-none-eabi-
+export CROSS_COMPILE
+export CROSS_COMPILE_T32
 
 KCONFIG_CONFIG	?= .config
 export KCONFIG_CONFIG
