#!/bin/sh
#
# Starts audioservice.
#


start() {
	printf "Starting audioservice: "
    /usr/bin/audioservice /etc/default_audioservice.conf&
    echo "OK"
}
stop() {
	printf "Stopping audioservice: "
  #/usb/bin/asplay.py exit
  killall audioservice
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

